# 1. Set your GitHub default branch to dev/develop
# 2. In circleci project settings->advanced set:
#    - GitHub Status Updates (this should be on already)
#    - Only build pull requests
#    - Auto-cancel redundant builds
#    - Free and Open Source (this should be on already)
# 3. If existing project with quay.io, remove the quay build triggers.
#    - as circleci is pusing the image
#    - reevaluate when/if quay.io adds ability to authenticate pulls

version: 2.1
jobs:
  license_chk:
    machine:
      # need machine as want to mount a volume
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run:
          name: Execute skywalking-eyes check of licenses
          command: |
            docker run --rm -v $(pwd):/github/workspace apache/skywalking-eyes header check

  pre-commit:
    description: |
      Runs pre-commit hooks on precommit.ci
    docker:
      - image: python:3.7.5
    steps:
      - checkout
      - run:
          command: |
            ls -la ./
            cp .pre-commit-config.yaml pre-commit-cache-key.txt
            python --version --version >> pre-commit-cache-key.txt
      - restore_cache:
          keys:
          - v1-pc-cache-{{ checksum "pre-commit-cache-key.txt" }}
      - run:
          command: pip install pre-commit
      - run:
          command: pre-commit run --all-files
      - save_cache:
          key: v1-pc-cache-{{ checksum "pre-commit-cache-key.txt" }}
          paths:
          - ~/.cache/pre-commit

  build:
    environment:
      IMAGE_NAME: quay.io/wtsicgp/casm-smart-phase
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            set -e
            BRANCH_OR_TAG="${CIRCLE_TAG:-$CIRCLE_BRANCH}"
            CLEAN_BRANCH=$(echo $BRANCH_OR_TAG | tr / -)
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
            echo "$QUAYIO_PASSWORD" | docker login -u "$QUAYIO_USER" --password-stdin quay.io
            docker build -t $IMAGE_NAME:$CLEAN_BRANCH .
            echo 'Verify program(s) from this repo'
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH casmsmartphase generate-bed --version
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH casmsmartphase merge-mnvs --version
            docker run -t --rm $IMAGE_NAME:$CLEAN_BRANCH java -jar /opt/wsi-t78/smartPhase.jar -h
            if [ "$CIRCLE_TAG" = "$BRANCH_OR_TAG" ]; then
              echo 'Pushing image'
              docker push $IMAGE_NAME:$CLEAN_BRANCH
            else
              echo "I am not a tag so not pushing image"
            fi
workflows:
  version: 2.1
  build_test:
    jobs:
      - license_chk:
          filters:
            tags:
              only: /.+/
      - pre-commit:
          filters:
            tags:
              only: /.+/
      - build:
          context:
            - dockerhub-casmservice
            - quayio-casmservice
          filters:
            tags:
              only: /.+/
